# syntax=docker/dockerfile:1

FROM {{ .BaseImage }}

LABEL com.docker.agent.packaging.version="v0.0.2"
LABEL com.docker.agent.runtime="cagent"
LABEL com.docker.agent.secrets.models="{{ .ModelSecrets }}"
LABEL com.docker.agent.secrets.tools="{{ .ToolSecrets }}"

LABEL org.opencontainers.image.author="{{ .Metadata.Author }}"
LABEL org.opencontainers.image.created="{{ .BuildDate }}"
LABEL org.opencontainers.image.description="{{ .Description }}"
LABEL org.opencontainers.image.documentation="{{ .Metadata.Readme }}"
LABEL org.opencontainers.image.licenses="{{ .Metadata.License }}"

# Override labels found in docker/cagent until we know what to put there
LABEL org.opencontainers.image.revision=""
LABEL org.opencontainers.image.source=""
LABEL org.opencontainers.image.title=""
LABEL org.opencontainers.image.url=""
LABEL org.opencontainers.image.version=""

VOLUME /data
ENV TELEMETRY_ENABLED=true
ENV CAGENT_HIDE_TELEMETRY_BANNER=0
USER root
RUN cat <<EOF >/agent.yaml && chmod 777 /agent.yaml
{{ .AgentConfig }}
EOF
USER cagent
CMD ["api", "--listen", "unix:///data/agent.sock", "--session-db", "/data/session.db", "/agent.yaml"]
