# syntax=docker/dockerfile:1

FROM docker/cagent
LABEL com.docker.agent.packaging.version="v0.0.1"
LABEL com.docker.agent.runtime="cagent"
LABEL org.opencontainers.image.description="{{ .Description }}"
LABEL org.opencontainers.image.licenses="{{ .Licenses }}"
LABEL com.docker.agent.mcp-servers="{{ .McpServers }}"
LABEL com.docker.agent.models="{{ .Models }}"
VOLUME /data
CMD ["api", "--session-db", "/data/session.db", "/agent.yaml"]
RUN cat <<EOF >/agent.yaml
{{ .AgentConfig }}
EOF
